//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Core.Properties.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra lại code. Hiện đang có lỗi phần backend!.
        /// </summary>
        internal static string DevMsg_Erro500 {
            get {
                return ResourceManager.GetString("DevMsg_Erro500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File gửi lên rỗng !.
        /// </summary>
        internal static string DevNullFile {
            get {
                return ResourceManager.GetString("DevNullFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không để trống !.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được để trống !.
        /// </summary>
        internal static string EmptyCustomerCode {
            get {
                return ResourceManager.GetString("EmptyCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vị trí không được để trống !.
        /// </summary>
        internal static string EmptyDepartmentCode {
            get {
                return ResourceManager.GetString("EmptyDepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống !.
        /// </summary>
        internal static string EmptyEmployeeCode {
            get {
                return ResourceManager.GetString("EmptyEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được để trống !.
        /// </summary>
        internal static string EmptyPositonCode {
            get {
                return ResourceManager.GetString("EmptyPositonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ hiện đang có lỗi vui lòng liên hệ MISA để giải quyết.
        /// </summary>
        internal static string Erro500 {
            get {
                return ResourceManager.GetString("Erro500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email của bạn chưa đúng định dạng. Vui lòng kiểm tra lại !.
        /// </summary>
        internal static string FormatEmail {
            get {
                return ResourceManager.GetString("FormatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã này đã tồn tại. Bạn vui lòng chọn mã khác !.
        /// </summary>
        internal static string MatchCode {
            get {
                return ResourceManager.GetString("MatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng minh thư đã tồn tại !.
        /// </summary>
        internal static string MathIdentityNumber {
            get {
                return ResourceManager.GetString("MathIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu bạn gửi lên không hợp lệ. Vui lòng thử lại !.
        /// </summary>
        internal static string UserMsg_Erro400 {
            get {
                return ResourceManager.GetString("UserMsg_Erro400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống chưa được ủy quyền. Máy chủ từ chối yêu cầu của bạn !.
        /// </summary>
        internal static string UserMsg_Erro401 {
            get {
                return ResourceManager.GetString("UserMsg_Erro401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ từ chối yêu cầu của bạn !.
        /// </summary>
        internal static string UserMsg_Erro403 {
            get {
                return ResourceManager.GetString("UserMsg_Erro403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ không tìm thấy dữ liệu tương ứng với dữ liệu bạn gửi lên!.
        /// </summary>
        internal static string UserMsg_Erro404 {
            get {
                return ResourceManager.GetString("UserMsg_Erro404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tệp nhập liệu !.
        /// </summary>
        internal static string UserNullFile {
            get {
                return ResourceManager.GetString("UserNullFile", resourceCulture);
            }
        }
    }
}
